(lang dune 3.21)

(name rook)

(generate_opam_files true)

(source
 (github jargenn/blog))

(authors "Acosta Quintana Lautaro <me@lautaroacosta.com>")

(maintainers "Acosta Quintana Lautaro <me@lautaroacosta.com>")

(license LICENSE)

(documentation https://url/to/documentation)

(package
 (name rook)
 (synopsis "A short synopsis")
 (description "A longer description")
 (depends ocaml)
 (tags
  ("add topics" "to describe" your project)))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
